name: build documentation and publish - upgradeService

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_UPGRADESERVICE }}
        with:
          source-directory: 'src'
          destination-github-username: 'Anime-Manga'
          destination-repository-name: 'upgradeService'
          target-branch: dev
          target-directory: 'src/references'
