name: build documentation and publish - apiService

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'src'
          destination_repo: 'Anime-Manga/apiService'
          destination_folder: 'src/references'
          user_email: 'mattia.ceschin@gmail.com'
          user_name: 'cesxhin'
          destination_branch: 'dev'
          commit_message: 'Update references'
